### ISSUE TITLE
@MofhyDeveloper MofhyDeveloper released this 3 minutes ago

### ISSUE THREAD

**Issue by ImLoadingUuU** [MofhyDevs/NewAccountNotice#1]
<img width="1679" alt="截圖 2022-02-16 下午2 26 17" src="https://user-images.githubusercontent.com/69704016/154208499-4e963ef8-09b2-43e4-907e-327ca904565c.png">
hehe

**Comment by MofhyDeveloper** [comment]
What happened? I don't see any issue related in your post. @ImLoadingUuU

**Comment by ImLoadingUuU** [comment]
nothing just flex(means show off)i see this 3 minutes ago hehe

**Comment by MofhyDeveloper** [comment]
Ok
